# k8s/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: terraform-agent-config
  namespace: terraform-agent
  labels:
    app: terraform-agent
data:
  LOG_LEVEL: "INFO"
  MAX_CONCURRENT_REQUESTS: "10"
  GITHUB_REPO: "terraform-infrastructure"
