# k8s/pdb.yaml (Pod Disruption Budget)
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: terraform-agent-pdb
  namespace: terraform-agent
  labels:
    app: terraform-agent
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: terraform-agent
