# k8s/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: terraform-agent-rolebinding
  namespace: terraform-agent
  labels:
    app: terraform-agent
subjects:
- kind: ServiceAccount
  name: terraform-agent-sa
  namespace: terraform-agent
roleRef:
  kind: Role
  name: terraform-agent-role
  apiGroup: rbac.authorization.k8s.io
